name: Daily Instagram Follower Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: read
  actions: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Verify Secrets
      run: |
        if [ -z "${{ secrets.INSTAGRAM_USERNAME }}" ]; then
          echo "Error: INSTAGRAM_USERNAME is not set"
          exit 1
        fi
        if [ -z "${{ secrets.INSTAGRAM_PASSWORD }}" ]; then
          echo "Error: INSTAGRAM_PASSWORD is not set"
          exit 1
        fi
        if [ -z "${{ secrets.MONGODB_URI }}" ]; then
          echo "Error: MONGODB_URI is not set"
          exit 1
        fi
        echo "✓ All required secrets are set"
        
    - name: Test MongoDB Connection
      run: |
        echo "const { MongoClient } = require('mongodb');
        async function testConnection() {
          const client = new MongoClient('${{ secrets.MONGODB_URI }}');
          try {
            await client.connect();
            console.log('MongoDB connection successful');
            const db = client.db('instagram_bot');
            await db.command({ ping: 1 });
            console.log('Database ping successful');
          } catch (error) {
            console.error('MongoDB connection failed:', error);
            process.exit(1);
          } finally {
            await client.close();
          }
        }
        testConnection();" > test-mongo-connection.js
        node test-mongo-connection.js
        
    - name: Create .env file
      run: |
        echo "INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }}" > .env
        echo "INSTAGRAM_PASSWORD=${{ secrets.INSTAGRAM_PASSWORD }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        
    - name: Run scraper
      run: node followerScraper.js
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      
    - name: Cleanup
      if: always()
      run: |
        rm -f .env
        rm -f test-mongo-connection.js 